```{r}
pacman::p_load(caTools)
pacman::p_load(Metrics)
pacman::p_load(e1071)
pacman::p_load(xgboost)
pacman::p_load(caret)
pacman::p_load(dplyr)
pacman::p_load(tidyverse)
```

#data pre processing
```{r}
featureSelection <- function(data) {
  # Highly correlated features
  correlationMatrix <- cor(data[, names(data) != "pha"])
  
  # Index of highly correlation features
  hightlyCorrelated <- findCorrelation(correlationMatrix,
                                       cutoff = 0.9, names = TRUE)
  
  # Remove highly correlated features
  data <- data[, !names(data) %in% hightlyCorrelated]
  return(data)
}


dataCleaning <- function(data) {
  # Remove unnecessary field
  data <- data[, !names(data)
               %in% c("prefix", "id", "spkid", "full_name", "pdes",
                      "name", "orbit_id", "equinox", "neo", "class")]
  
  # Remove NA data
  data <- na.omit(data)
  
  # Categorical data
  data <- transform(
    data,
    pha = as.factor(pha)
  )
  
  return(data)
}
```

```{r}
data=read.csv("dataset.csv")
head(data)
data$pha=as.factor(data$pha)
```

```{r}
data1=dataCleaning(data)
data2=featureSelection(data1)
head(data2)
```

```{r}
data2$pha <- ifelse(data2$pha == 'N', 0, 1)
sample = sample.split(data2$pha, SplitRatio = 0.75)
train = subset(data2, sample == TRUE)
test = subset(data2, sample == FALSE)
```

```{r}
pacman::p_load(mda)
summary(train)
model <- mda(pha~., data = train)
predictions <- model %>% predict(test)
# Model accuracy
mean(predictions$class==test$pha)
```


```{r}

xgb <- xgboost(data = data.matrix(data2[,-1]), 
 label = y, 
 eta = 0.1,
 max_depth = 15, 
 nround=25, 
 subsample = 0.5,
 colsample_bytree = 0.5,
 seed = 1,
 eval_metric = "merror",
 objective = "multi:softprob",
 num_class = 2,
 nthread = 3
)
```

```{r}
y_pred <- predict(xgb, data.matrix(data2[,-1]))
length(y_pred)
y_pred <- ifelse(y_pred > 0.5,1,0)
length(y_pred)
```
```{r}
y <- data2$pha
length(y)
y_test <- ifelse(unlist(y) == 'N', 0, 1)
length(y_pred)
length(y_test)
sum(is.na(data2))
example <- confusionMatrix(data=as.factor(y_pred), reference = as.factor(y_test))
example
```

```{r}
pred$confusion
```

